# Generated by Django 6.0.1 on 2026-01-28 11:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='event_images')),
            ],
            options={
                'verbose_name': 'Изображение мероприятие',
                'verbose_name_plural': 'Изображения мероприятия',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.IntegerField(default=0, verbose_name='цена от')),
                ('max_price', models.IntegerField(blank=True, null=True, verbose_name='цена до')),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='номер телефона')),
                ('instagram', models.CharField(blank=True, max_length=255, null=True, verbose_name='инстаграм')),
                ('event_status', models.CharField(blank=True, max_length=255, null=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('event_time', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('is_banned', models.BooleanField(default=False, verbose_name='Запрещенный')),
                ('on_moderation', models.BooleanField(default=True, verbose_name='На модерации')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('views', models.PositiveIntegerField(default=0, verbose_name='количество просмотров')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.city', verbose_name='город')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.district', verbose_name='район')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'ordering': ('id',),
            },
        ),
    ]
