# Generated by Django 6.0.1 on 2026-01-28 11:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.IntegerField(default=0, verbose_name='цена')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('is_banned', models.BooleanField(default=False, verbose_name='Запрещенный')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('views', models.PositiveIntegerField(default=0, verbose_name='количество просмотров')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.category', verbose_name='категория')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.city', verbose_name='город')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.district', verbose_name='район')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.subcategory', verbose_name='суб категория')),
                ('under_sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.undersubcategory', verbose_name='андер суб категория')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявлении',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='AnnouncementImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='announcement_images')),
            ],
            options={
                'verbose_name': 'Изображение объявления',
                'verbose_name_plural': 'Изображения объявлений',
            },
        ),
        migrations.CreateModel(
            name='BannedAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('announcement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='announcement.announcement')),
                ('type_of_accessories', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Тип Аксесуаров')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='Состояние')),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='Бренд')),
                ('gender', models.CharField(blank=True, max_length=50, null=True, verbose_name='Пол')),
            ],
            bases=('announcement.announcement',),
        ),
        migrations.CreateModel(
            name='BeautyHealth',
            fields=[
                ('announcement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='announcement.announcement')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='Состояние')),
            ],
            bases=('announcement.announcement',),
        ),
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('announcement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='announcement.announcement')),
                ('type_of_cloth', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Тип одежды')),
                ('gender', models.CharField(blank=True, max_length=50, null=True, verbose_name='Пол')),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.CharField(blank=True, max_length=25, null=True, verbose_name='Размер')),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='Бренд')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='Состояние')),
            ],
            bases=('announcement.announcement',),
        ),
        migrations.CreateModel(
            name='Electronics',
            fields=[
                ('announcement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='announcement.announcement')),
                ('type_electronic', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Тип электроники')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='Состояние')),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=50, null=True, verbose_name='Производитель')),
            ],
            bases=('announcement.announcement',),
        ),
        migrations.CreateModel(
            name='LookingEmployee',
            fields=[
                ('announcement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='announcement.announcement')),
                ('schedule', models.CharField(blank=True, max_length=50, null=True, verbose_name='График работы')),
                ('payment', models.CharField(blank=True, max_length=50, null=True, verbose_name='Оплата')),
                ('experience', models.CharField(blank=True, max_length=50, null=True, verbose_name='Опыт работы')),
                ('gender', models.CharField(blank=True, max_length=50, null=True, verbose_name='Пол')),
            ],
            bases=('announcement.announcement',),
        ),
        migrations.CreateModel(
            name='LookingJob',
            fields=[
                ('announcement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='announcement.announcement')),
                ('schedule', models.CharField(blank=True, max_length=50, null=True, verbose_name='График работы')),
                ('wage', models.IntegerField(blank=True, default=0, null=True, verbose_name='Заработная плата')),
                ('experience', models.CharField(blank=True, max_length=50, null=True, verbose_name='Опыт работы')),
            ],
            bases=('announcement.announcement',),
        ),
        migrations.CreateModel(
            name='ProductsForChildren',
            fields=[
                ('announcement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='announcement.announcement')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='Состояние')),
            ],
            bases=('announcement.announcement',),
        ),
        migrations.CreateModel(
            name='RealEstates',
            fields=[
                ('announcement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='announcement.announcement')),
                ('type_housing', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Тип жилья')),
                ('price_estate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость')),
                ('number_of_rooms', models.CharField(blank=True, max_length=255, null=True, verbose_name='Количество комнат')),
                ('swimming_pool', models.BooleanField(default=False, verbose_name='Наличие бассейна')),
                ('with_photo', models.BooleanField(default=False, verbose_name='Объявление с фото')),
            ],
            bases=('announcement.announcement',),
        ),
        migrations.CreateModel(
            name='ServicesCargoTransportation',
            fields=[
                ('announcement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='announcement.announcement')),
                ('availability_of_loaders', models.BooleanField(blank=True, default=False, null=True, verbose_name='Наличие грузчиков')),
            ],
            bases=('announcement.announcement',),
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('announcement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='announcement.announcement')),
                ('type_of_shoes', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Тип обуви')),
                ('gender', models.CharField(blank=True, max_length=50, null=True, verbose_name='Пол')),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.CharField(blank=True, max_length=25, null=True, verbose_name='Размер')),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='Бренд')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='Состояние')),
            ],
            bases=('announcement.announcement',),
        ),
        migrations.CreateModel(
            name='TransportRental',
            fields=[
                ('announcement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='announcement.announcement')),
                ('rental_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='цена аренды')),
            ],
            bases=('announcement.announcement',),
        ),
    ]
