# Generated by Django 6.0.1 on 2026-01-28 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('announcement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользовател'),
        ),
        migrations.AddField(
            model_name='announcementimage',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='announcement.announcement'),
        ),
        migrations.AddField(
            model_name='bannedannouncement',
            name='announcement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='announcement.announcement'),
        ),
        migrations.AddField(
            model_name='bannedannouncement',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('realestates_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='announcement.realestates')),
                ('type_estate', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Тип недвижимость')),
            ],
            bases=('announcement.realestates',),
        ),
        migrations.CreateModel(
            name='TakeOff',
            fields=[
                ('realestates_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='announcement.realestates')),
                ('rules', models.CharField(blank=True, max_length=50, null=True, verbose_name='Правила')),
            ],
            bases=('announcement.realestates',),
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('transportrental_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='announcement.transportrental')),
                ('rental_type', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Тип аренды')),
                ('deposit', models.BooleanField(blank=True, default=None, null=True, verbose_name='Депозит')),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery', models.BooleanField(blank=True, default=None, null=True, verbose_name='Доставка')),
                ('child_seat', models.BooleanField(default=False, verbose_name='Детское кресло')),
                ('phone_charger', models.BooleanField(default=False, verbose_name='Зарядное устройство для телефона')),
                ('audio_system', models.BooleanField(default=False, verbose_name='Аудиосистема')),
            ],
            bases=('announcement.transportrental',),
        ),
        migrations.CreateModel(
            name='Mopeds',
            fields=[
                ('transportrental_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='announcement.transportrental')),
                ('rental_type', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Тип аренды')),
                ('deposit', models.BooleanField(blank=True, default=None, null=True, verbose_name='Депозит')),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery', models.BooleanField(blank=True, default=None, null=True, verbose_name='Доставка')),
                ('phone_mount', models.BooleanField(default=False, verbose_name='Крепление для телефона')),
            ],
            bases=('announcement.transportrental',),
        ),
        migrations.CreateModel(
            name='Motorcycles',
            fields=[
                ('transportrental_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='announcement.transportrental')),
                ('rental_type', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Тип аренды')),
                ('deposit', models.BooleanField(blank=True, default=None, null=True, verbose_name='Депозит')),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery', models.BooleanField(blank=True, default=None, null=True, verbose_name='Доставка')),
                ('child_seat', models.BooleanField(default=False, verbose_name='Детское кресло')),
                ('phone_charger', models.BooleanField(default=False, verbose_name='Зарядное устройство для телефона')),
                ('audio_system', models.BooleanField(default=False, verbose_name='Аудиосистема')),
                ('engine_capacity', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Объем двигателя, см³')),
            ],
            bases=('announcement.transportrental',),
        ),
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('transportrental_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='announcement.transportrental')),
                ('vehicle_type', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Вид транспорта')),
                ('service_type', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Вид услуги')),
                ('drive', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Поездка')),
                ('child_seat', models.BooleanField(default=False, verbose_name='Детское кресло')),
                ('phone_charger', models.BooleanField(default=False, verbose_name='Зарядное устройство для телефона')),
                ('meeting_with_sign', models.BooleanField(default=False, verbose_name='Встреча с табличкой')),
            ],
            bases=('announcement.transportrental',),
        ),
    ]
